version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app
    command: npm run dev

  test:
    build: .
    environment:
      - NODE_ENV=test
    volumes:
      - .:/app
    command: npm test

  cypress:
    image: cypress/included:13.13.1
    depends_on:
      - app
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CYPRESS_BASE_URL=http://app:3000
    entrypoint: npx cypress run --headless

volumes:
  node_modules:
