name: CI/CD Pipeline for Staging

on:
  # 機能ごとのブランチのプルリクエスト作成時にテストを実行
  pull_request:
    branches:
      - '**'  # すべてのブランチからのプルリクエストをトリガー
  # stagingブランチへのプッシュでデプロイをトリガー
  push:
    branches:
      - staging

jobs:
  test:
    # JestとCypressのテストを実行
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test -- --passWithNoTests

      # - name: Run Cypress tests
      #   run: npm run cypress:run -- --headless  # ヘッドレスモードで実行

  build-and-deploy:
    # Stagingブランチへのプッシュ時にデプロイを実行
    runs-on: ubuntu-latest
    needs: test  # テストジョブが成功した後に実行
    if: github.ref == 'refs/heads/staging'  # stagingブランチへのプッシュのみデプロイ
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 --build-arg ENV_FILE=.env.staging -t gcr.io/re-light-staging-435705/my-app-staging .

      - name: Push Docker image to GCR
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/my-app-staging

      - name: Deploy to Cloud Run
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${{ env.GCP_PROJECT_ID }}
          gcloud run deploy re-light-staging \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/my-app-staging \
            --region asia-northeast2 \
            --platform managed \
            --allow-unauthenticated
